package model.EO;

import java.math.BigDecimal;

import java.sql.SQLException;
import java.sql.Timestamp;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 13:52:29 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcGatePassDetailsImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LineId,
        DetailId,
        LineCode,
        ItemId,
        Quantity,
        Uom,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        RefLineId,
        ItemDesc,
        ItemDetails,
        SourceId,
        SecondaryQty,
        Remarks,
        SecondaryUom,
        PwcGatePassLinesEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int REFLINEID = AttributesEnum.RefLineId.index();
    public static final int ITEMDESC = AttributesEnum.ItemDesc.index();
    public static final int ITEMDETAILS = AttributesEnum.ItemDetails.index();
    public static final int SOURCEID = AttributesEnum.SourceId.index();
    public static final int SECONDARYQTY = AttributesEnum.SecondaryQty.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int SECONDARYUOM = AttributesEnum.SecondaryUom.index();
    public static final int PWCGATEPASSLINESEO = AttributesEnum.PwcGatePassLinesEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcGatePassDetailsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.PwcGatePassDetails");
    }


    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the value of LineId
     */
    public BigDecimal getLineId() {
        return (BigDecimal) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(BigDecimal value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for DetailId, using the alias name DetailId.
     * @return the value of DetailId
     */
    public oracle.jbo.domain.Number getDetailId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as the attribute value for DetailId.
     * @param value value to set the DetailId
     */
    public void setDetailId(oracle.jbo.domain.Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for LineCode, using the alias name LineCode.
     * @return the value of LineCode
     */
    public String getLineCode() {
        return (String) getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineCode.
     * @param value value to set the LineCode
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the value of ItemId
     */
    public BigDecimal getItemId() {
        return (BigDecimal) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(BigDecimal value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for Quantity, using the alias name Quantity.
     * @return the value of Quantity
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Quantity.
     * @param value value to set the Quantity
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for Uom, using the alias name Uom.
     * @return the value of Uom
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uom.
     * @param value value to set the Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }


    /**
     * Gets the attribute value for RefLineId, using the alias name RefLineId.
     * @return the value of RefLineId
     */
    public Number getRefLineId() {
        return (Number) getAttributeInternal(REFLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefLineId.
     * @param value value to set the RefLineId
     */
    public void setRefLineId(Number value) {
        setAttributeInternal(REFLINEID, value);
    }

    /**
     * Gets the attribute value for ItemDesc, using the alias name ItemDesc.
     * @return the value of ItemDesc
     */
    public String getItemDesc() {
        return (String) getAttributeInternal(ITEMDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDesc.
     * @param value value to set the ItemDesc
     */
    public void setItemDesc(String value) {
        setAttributeInternal(ITEMDESC, value);
    }

    /**
     * Gets the attribute value for ItemDetails, using the alias name ItemDetails.
     * @return the value of ItemDetails
     */
    public String getItemDetails() {
        return (String) getAttributeInternal(ITEMDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemDetails.
     * @param value value to set the ItemDetails
     */
    public void setItemDetails(String value) {
        setAttributeInternal(ITEMDETAILS, value);
    }

    /**
     * Gets the attribute value for SourceId, using the alias name SourceId.
     * @return the value of SourceId
     */
    public BigDecimal getSourceId() {
        return (BigDecimal) getAttributeInternal(SOURCEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceId.
     * @param value value to set the SourceId
     */
    public void setSourceId(BigDecimal value) {
        setAttributeInternal(SOURCEID, value);
    }

    /**
     * Gets the attribute value for SecondaryQty, using the alias name SecondaryQty.
     * @return the value of SecondaryQty
     */
    public BigDecimal getSecondaryQty() {
        return (BigDecimal) getAttributeInternal(SECONDARYQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecondaryQty.
     * @param value value to set the SecondaryQty
     */
    public void setSecondaryQty(BigDecimal value) {
        setAttributeInternal(SECONDARYQTY, value);
    }

    /**
     * Gets the attribute value for Remarks, using the alias name Remarks.
     * @return the value of Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Remarks.
     * @param value value to set the Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for SecondaryUom, using the alias name SecondaryUom.
     * @return the value of SecondaryUom
     */
    public String getSecondaryUom() {
        return (String) getAttributeInternal(SECONDARYUOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for SecondaryUom.
     * @param value value to set the SecondaryUom
     */
    public void setSecondaryUom(String value) {
        setAttributeInternal(SECONDARYUOM, value);
    }

    /**
     * @return the associated entity PwcGatePassLinesEOImpl.
     */
    public PwcGatePassLinesEOImpl getPwcGatePassLinesEO() {
        return (PwcGatePassLinesEOImpl) getAttributeInternal(PWCGATEPASSLINESEO);
    }

    /**
     * Sets <code>value</code> as the associated entity PwcGatePassLinesEOImpl.
     */
    public void setPwcGatePassLinesEO(PwcGatePassLinesEOImpl value) {
        setAttributeInternal(PWCGATEPASSLINESEO, value);
    }


    /**
     * @param detailId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number detailId) {
        return new Key(new Object[] { detailId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl s =
            new oracle.jbo.server.SequenceImpl("PWC_GATE_PASS_DETAILS_S",
                                               getDBTransaction());
        oracle.jbo.domain.Number sVal = s.getSequenceNumber();
        setDetailId(sVal);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
        
//        Map sessionScope = ADFContext.getCurrent().getSessionScope();
//        String userId = (String)sessionScope.get("UserId");
//        
//        try {
//            setLastUpdatedBy(new oracle.jbo.domain.Number(userId));
//        } catch (SQLException sqle) {
//            // TODO: Add catch code
//            sqle.printStackTrace();
//        }
//        
//        if (DML_INSERT == operation) {
//            try {
//                setCreatedBy(new oracle.jbo.domain.Number(userId));
//            } catch (SQLException sqle) {
//                // TODO: Add catch code
//                sqle.printStackTrace();
//            }
//        } else if (DML_UPDATE == operation) {
//            try {
//                setLastUpdatedBy(new oracle.jbo.domain.Number(userId));
//            } catch (SQLException sqle) {
//                // TODO: Add catch code
//                sqle.printStackTrace();
//            }
//        }
    }
}

