package model.EO;

import java.math.BigDecimal;

import java.sql.SQLException;
import java.sql.Timestamp;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.NClobDomain;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 13:50:12 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcGatePassLinesEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HeaderId,
        LineId,
        LineCode,
        DeliveryChallanNo,
        Source,
        SourceDocNo,
        CreatedBy,
        CreationDate,
        LastUpdateDate,
        LastUpdatedBy,
        RefLineId,
        ShipToLocation,
        PwcGatePassHeaderEO,
        PwcGatePassDetails;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int DELIVERYCHALLANNO = AttributesEnum.DeliveryChallanNo.index();
    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int SOURCEDOCNO = AttributesEnum.SourceDocNo.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int REFLINEID = AttributesEnum.RefLineId.index();
    public static final int SHIPTOLOCATION = AttributesEnum.ShipToLocation.index();
    public static final int PWCGATEPASSHEADEREO = AttributesEnum.PwcGatePassHeaderEO.index();
    public static final int PWCGATEPASSDETAILS = AttributesEnum.PwcGatePassDetails.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcGatePassLinesEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.EO.PwcGatePassLinesEO");
    }


    /**
     * Gets the attribute value for HeaderId, using the alias name HeaderId.
     * @return the value of HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for HeaderId.
     * @param value value to set the HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for LineId, using the alias name LineId.
     * @return the value of LineId
     */
    public oracle.jbo.domain.Number getLineId() {
        return (oracle.jbo.domain.Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineId.
     * @param value value to set the LineId
     */
    public void setLineId(oracle.jbo.domain.Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for LineCode, using the alias name LineCode.
     * @return the value of LineCode
     */
    public String getLineCode() {
        return (String) getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LineCode.
     * @param value value to set the LineCode
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for DeliveryChallanNo, using the alias name DeliveryChallanNo.
     * @return the value of DeliveryChallanNo
     */
    public String getDeliveryChallanNo() {
        return (String) getAttributeInternal(DELIVERYCHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryChallanNo.
     * @param value value to set the DeliveryChallanNo
     */
    public void setDeliveryChallanNo(String value) {
        setAttributeInternal(DELIVERYCHALLANNO, value);
    }

    /**
     * Gets the attribute value for Source, using the alias name Source.
     * @return the value of Source
     */
    public String getSource() {
        return (String) getAttributeInternal(SOURCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Source.
     * @param value value to set the Source
     */
    public void setSource(String value) {
        setAttributeInternal(SOURCE, value);
    }

    /**
     * Gets the attribute value for SourceDocNo, using the alias name SourceDocNo.
     * @return the value of SourceDocNo
     */
    public String getSourceDocNo() {
        return (String) getAttributeInternal(SOURCEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SourceDocNo.
     * @param value value to set the SourceDocNo
     */
    public void setSourceDocNo(String value) {
        setAttributeInternal(SOURCEDOCNO, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the value of CreationDate
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }


    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }


    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }


    /**
     * Gets the attribute value for RefLineId, using the alias name RefLineId.
     * @return the value of RefLineId
     */
    public BigDecimal getRefLineId() {
        return (BigDecimal) getAttributeInternal(REFLINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for RefLineId.
     * @param value value to set the RefLineId
     */
    public void setRefLineId(BigDecimal value) {
        setAttributeInternal(REFLINEID, value);
    }

    /**
     * Gets the attribute value for ShipToLocation, using the alias name ShipToLocation.
     * @return the value of ShipToLocation
     */
    public String getShipToLocation() {
        return (String) getAttributeInternal(SHIPTOLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipToLocation.
     * @param value value to set the ShipToLocation
     */
    public void setShipToLocation(String value) {
        setAttributeInternal(SHIPTOLOCATION, value);
    }

    /**
     * @return the associated entity PwcGatePassHeaderEOImpl.
     */
    public PwcGatePassHeaderEOImpl getPwcGatePassHeaderEO() {
        return (PwcGatePassHeaderEOImpl) getAttributeInternal(PWCGATEPASSHEADEREO);
    }

    /**
     * Sets <code>value</code> as the associated entity PwcGatePassHeaderEOImpl.
     */
    public void setPwcGatePassHeaderEO(PwcGatePassHeaderEOImpl value) {
        setAttributeInternal(PWCGATEPASSHEADEREO, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getPwcGatePassDetails() {
        return (RowIterator) getAttributeInternal(PWCGATEPASSDETAILS);
    }


    /**
     * @param lineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[] { lineId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        String approvalStatus = null;
        try{
            approvalStatus = getPwcGatePassHeaderEO().getAttribute("ApprovalStatus").toString();    
        }catch(Exception e){
            ;    
        }
        
        if(approvalStatus != null && (approvalStatus.equals("I") || approvalStatus.equals("Y"))){
            ;    
        }else{
            super.create(attributeList);
            oracle.jbo.server.SequenceImpl s =
                new oracle.jbo.server.SequenceImpl("PWC_GATE_PASS_LINES_S",
                                                   getDBTransaction());
            oracle.jbo.domain.Number sVal = s.getSequenceNumber();
            setLineId(sVal);    
        }
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        
        
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        String userId = (String)sessionScope.get("UserId");
        
//        try {
//            setLastUpdatedBy(new oracle.jbo.domain.Number(userId));
//        } catch (SQLException sqle) {
//            // TODO: Add catch code
//            sqle.printStackTrace();
//        }
//        
        if (DML_UPDATE == operation) {
            try {
                setLastUpdatedBy(new oracle.jbo.domain.Number(userId));
            } catch (SQLException sqle) {
                // TODO: Add catch code
                sqle.printStackTrace();
            }
        } else if (DML_INSERT == operation) {
            
            try {
                setCreatedBy(new oracle.jbo.domain.Number(userId));
            } catch (SQLException sqle) {
                // TODO: Add catch code
                sqle.printStackTrace();
            }
        }
        super.doDML(operation, e);
    }
}

