package model.VO;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 28 15:35:57 BDT 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GatePassAdminProfileVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        ProfileOptionName,
        UserProfileOptionName,
        ProfileOptionValue;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PROFILEOPTIONNAME = AttributesEnum.ProfileOptionName.index();
    public static final int USERPROFILEOPTIONNAME = AttributesEnum.UserProfileOptionName.index();
    public static final int PROFILEOPTIONVALUE = AttributesEnum.ProfileOptionValue.index();

    /**
     * This is the default constructor (do not remove).
     */
    public GatePassAdminProfileVORowImpl() {
    }
}

