package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 28 15:35:57 BDT 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class GatePassAdminProfileVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public GatePassAdminProfileVOImpl() {
    }
}

