package model.VO;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 21 10:53:13 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateSearchLinesDataRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GatePassClass,
        LineCode,
        LineId,
        DeliveryChallanNo,
        Source,
        SourceDocNo,
        GatePassNo;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return PopulateSearchLinesDataRVORowImpl.AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return PopulateSearchLinesDataRVORowImpl.AttributesEnum.firstIndex() +
                   PopulateSearchLinesDataRVORowImpl.AttributesEnum
                                                                                                                    .staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = PopulateSearchLinesDataRVORowImpl.AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int GATEPASSCLASS = AttributesEnum.GatePassClass.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int DELIVERYCHALLANNO = AttributesEnum.DeliveryChallanNo.index();
    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int SOURCEDOCNO = AttributesEnum.SourceDocNo.index();
    public static final int GATEPASSNO = AttributesEnum.GatePassNo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateSearchLinesDataRVORowImpl() {
    }
}

