package model.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 26 12:05:53 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateSearchDataHeaderRVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        GatePassClass,
        GatePassType,
        GatePassDate,
        GatePassNo,
        PartyToId,
        PartyToAddress,
        VehicleType,
        OuId,
        OperatingUnit,
        VehicleNo,
        DriverName,
        DriverPhone,
        Returnable,
        IsReturned,
        PartyTo;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int GATEPASSCLASS = AttributesEnum.GatePassClass.index();
    public static final int GATEPASSTYPE = AttributesEnum.GatePassType.index();
    public static final int GATEPASSDATE = AttributesEnum.GatePassDate.index();
    public static final int GATEPASSNO = AttributesEnum.GatePassNo.index();
    public static final int PARTYTOID = AttributesEnum.PartyToId.index();
    public static final int PARTYTOADDRESS = AttributesEnum.PartyToAddress.index();
    public static final int VEHICLETYPE = AttributesEnum.VehicleType.index();
    public static final int OUID = AttributesEnum.OuId.index();
    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int VEHICLENO = AttributesEnum.VehicleNo.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVERPHONE = AttributesEnum.DriverPhone.index();
    public static final int RETURNABLE = AttributesEnum.Returnable.index();
    public static final int ISRETURNED = AttributesEnum.IsReturned.index();
    public static final int PARTYTO = AttributesEnum.PartyTo.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateSearchDataHeaderRVORowImpl() {
    }
}

