package model.VO;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 18 23:18:28 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcDeleteBtnValidateVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PwcDeleteBtnValidateVOImpl() {
    }
}

