package model.VO;

import java.math.BigDecimal;

import model.EO.PwcGatePassHeaderEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Timestamp;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 13 12:18:43 BDT 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcGatePassHeaderVORowImpl extends ViewRowImpl {


    public static final int ENTITY_PWCGATEPASSHEADEREO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        HeaderId,
        CreatedBy,
        CreationDate,
        LastUpdateDate,
        LastUpdatedBy,
        GatePassClass,
        GatePassDate,
        GatePassType,
        GatePassNo,
        PartFromId,
        PartyToId,
        PartyFromAddress,
        PartyToAddress,
        OuId,
        VehicleType,
        VehicleNo,
        DriverName,
        DriverPhone,
        Returnable,
        IsReturned,
        RefGatePassNo,
        GateInDate,
        GateOutDate,
        GateInFlag,
        GateOutFlag,
        PartyFromName,
        PartyToName,
        OperatingUnit,
        CreaterName,
        LastEditorName,
        OperatingUnit1,
        TimeOutFlag,
        DisabledFlag,
        ApprovalStatus,
        Source,
        SourceDocNo,
        ApproveStatusMeaning,
        LocationId,
        Remarks,
        PartyAddressGeneric,
        OrganizationId,
        SumofLineQty,
        Org_Nam,
        Internal,
        Carrier,
        LicenceNo,
        LockNo,
        PwcGatePassLinesVO,
        PwcPopulateSearchVO,
        PartiesAddressLOV1,
        PartiesAddressLOV2,
        PartiesLOV1,
        PartiesLOV2,
        VehicleTypeLOV1,
        GatePassTypeLOV1,
        GatePassClass1,
        OperatingUnitsLOV1,
        RefGatePassLOV1,
        SourceLOV1,
        SourcesDocNoLOV1,
        ORG_NAME_LOV1,
        ORG_NAME_LOV2,
        ORG_NAME_LOV3,
        ORG_NAME_LOV4,
        ORG_NAME_LOV5,
        ORG_NAME_LOV6,
        ORG_NAME_LOV7,
        ORG_NAME_LOV8;
        private static AttributesEnum[] vals = null; ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int GATEPASSCLASS = AttributesEnum.GatePassClass.index();
    public static final int GATEPASSDATE = AttributesEnum.GatePassDate.index();
    public static final int GATEPASSTYPE = AttributesEnum.GatePassType.index();
    public static final int GATEPASSNO = AttributesEnum.GatePassNo.index();
    public static final int PARTFROMID = AttributesEnum.PartFromId.index();
    public static final int PARTYTOID = AttributesEnum.PartyToId.index();
    public static final int PARTYFROMADDRESS = AttributesEnum.PartyFromAddress.index();
    public static final int PARTYTOADDRESS = AttributesEnum.PartyToAddress.index();
    public static final int OUID = AttributesEnum.OuId.index();
    public static final int VEHICLETYPE = AttributesEnum.VehicleType.index();
    public static final int VEHICLENO = AttributesEnum.VehicleNo.index();
    public static final int DRIVERNAME = AttributesEnum.DriverName.index();
    public static final int DRIVERPHONE = AttributesEnum.DriverPhone.index();
    public static final int RETURNABLE = AttributesEnum.Returnable.index();
    public static final int ISRETURNED = AttributesEnum.IsReturned.index();
    public static final int REFGATEPASSNO = AttributesEnum.RefGatePassNo.index();
    public static final int GATEINDATE = AttributesEnum.GateInDate.index();
    public static final int GATEOUTDATE = AttributesEnum.GateOutDate.index();
    public static final int GATEINFLAG = AttributesEnum.GateInFlag.index();
    public static final int GATEOUTFLAG = AttributesEnum.GateOutFlag.index();
    public static final int PARTYFROMNAME = AttributesEnum.PartyFromName.index();
    public static final int PARTYTONAME = AttributesEnum.PartyToName.index();
    public static final int OPERATINGUNIT = AttributesEnum.OperatingUnit.index();
    public static final int CREATERNAME = AttributesEnum.CreaterName.index();
    public static final int LASTEDITORNAME = AttributesEnum.LastEditorName.index();
    public static final int OPERATINGUNIT1 = AttributesEnum.OperatingUnit1.index();
    public static final int TIMEOUTFLAG = AttributesEnum.TimeOutFlag.index();
    public static final int DISABLEDFLAG = AttributesEnum.DisabledFlag.index();
    public static final int APPROVALSTATUS = AttributesEnum.ApprovalStatus.index();
    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int SOURCEDOCNO = AttributesEnum.SourceDocNo.index();
    public static final int APPROVESTATUSMEANING = AttributesEnum.ApproveStatusMeaning.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int PARTYADDRESSGENERIC = AttributesEnum.PartyAddressGeneric.index();
    public static final int ORGANIZATIONID = AttributesEnum.OrganizationId.index();
    public static final int SUMOFLINEQTY = AttributesEnum.SumofLineQty.index();
    public static final int ORG_NAM = AttributesEnum.Org_Nam.index();
    public static final int INTERNAL = AttributesEnum.Internal.index();
    public static final int CARRIER = AttributesEnum.Carrier.index();
    public static final int LICENCENO = AttributesEnum.LicenceNo.index();
    public static final int LOCKNO = AttributesEnum.LockNo.index();
    public static final int PWCGATEPASSLINESVO = AttributesEnum.PwcGatePassLinesVO.index();
    public static final int PWCPOPULATESEARCHVO = AttributesEnum.PwcPopulateSearchVO.index();
    public static final int PARTIESADDRESSLOV1 = AttributesEnum.PartiesAddressLOV1.index();
    public static final int PARTIESADDRESSLOV2 = AttributesEnum.PartiesAddressLOV2.index();
    public static final int PARTIESLOV1 = AttributesEnum.PartiesLOV1.index();
    public static final int PARTIESLOV2 = AttributesEnum.PartiesLOV2.index();
    public static final int VEHICLETYPELOV1 = AttributesEnum.VehicleTypeLOV1.index();
    public static final int GATEPASSTYPELOV1 = AttributesEnum.GatePassTypeLOV1.index();
    public static final int GATEPASSCLASS1 = AttributesEnum.GatePassClass1.index();
    public static final int OPERATINGUNITSLOV1 = AttributesEnum.OperatingUnitsLOV1.index();
    public static final int REFGATEPASSLOV1 = AttributesEnum.RefGatePassLOV1.index();
    public static final int SOURCELOV1 = AttributesEnum.SourceLOV1.index();
    public static final int SOURCESDOCNOLOV1 = AttributesEnum.SourcesDocNoLOV1.index();
    public static final int ORG_NAME_LOV1 = AttributesEnum.ORG_NAME_LOV1.index();
    public static final int ORG_NAME_LOV2 = AttributesEnum.ORG_NAME_LOV2.index();
    public static final int ORG_NAME_LOV3 = AttributesEnum.ORG_NAME_LOV3.index();
    public static final int ORG_NAME_LOV4 = AttributesEnum.ORG_NAME_LOV4.index();
    public static final int ORG_NAME_LOV5 = AttributesEnum.ORG_NAME_LOV5.index();
    public static final int ORG_NAME_LOV6 = AttributesEnum.ORG_NAME_LOV6.index();
    public static final int ORG_NAME_LOV7 = AttributesEnum.ORG_NAME_LOV7.index();
    public static final int ORG_NAME_LOV8 = AttributesEnum.ORG_NAME_LOV8.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcGatePassHeaderVORowImpl() {
    }

    /**
     * Gets PwcGatePassHeaderEO entity object.
     * @return the PwcGatePassHeaderEO
     */
    public PwcGatePassHeaderEOImpl getPwcGatePassHeaderEO() {
        return (PwcGatePassHeaderEOImpl) getEntity(ENTITY_PWCGATEPASSHEADEREO);
    }

    /**
     * Gets the attribute value for HEADER_ID using the alias name HeaderId.
     * @return the HEADER_ID
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId.
     * @param value value to set the HEADER_ID
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for GATE_PASS_CLASS using the alias name GatePassClass.
     * @return the GATE_PASS_CLASS
     */
    public String getGatePassClass() {
        return (String) getAttributeInternal(GATEPASSCLASS);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_PASS_CLASS using the alias name GatePassClass.
     * @param value value to set the GATE_PASS_CLASS
     */
    public void setGatePassClass(String value) {
        setAttributeInternal(GATEPASSCLASS, value);
    }

    /**
     * Gets the attribute value for GATE_PASS_DATE using the alias name GatePassDate.
     * @return the GATE_PASS_DATE
     */
    public Timestamp getGatePassDate() {
        return (Timestamp) getAttributeInternal(GATEPASSDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_PASS_DATE using the alias name GatePassDate.
     * @param value value to set the GATE_PASS_DATE
     */
    public void setGatePassDate(Timestamp value) {
        setAttributeInternal(GATEPASSDATE, value);
    }

    /**
     * Gets the attribute value for GATE_PASS_TYPE using the alias name GatePassType.
     * @return the GATE_PASS_TYPE
     */
    public String getGatePassType() {
        return (String) getAttributeInternal(GATEPASSTYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_PASS_TYPE using the alias name GatePassType.
     * @param value value to set the GATE_PASS_TYPE
     */
    public void setGatePassType(String value) {
        setAttributeInternal(GATEPASSTYPE, value);
        if (value.equals("Transactional")) {
            this.setInternal("N");

        }
    }

    /**
     * Gets the attribute value for GATE_PASS_NO using the alias name GatePassNo.
     * @return the GATE_PASS_NO
     */
    public String getGatePassNo() {
        return (String) getAttributeInternal(GATEPASSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_PASS_NO using the alias name GatePassNo.
     * @param value value to set the GATE_PASS_NO
     */
    public void setGatePassNo(String value) {
        setAttributeInternal(GATEPASSNO, value);
    }

    /**
     * Gets the attribute value for PART_FROM_ID using the alias name PartFromId.
     * @return the PART_FROM_ID
     */
    public Number getPartFromId() {
        return (Number) getAttributeInternal(PARTFROMID);
    }

    /**
     * Sets <code>value</code> as attribute value for PART_FROM_ID using the alias name PartFromId.
     * @param value value to set the PART_FROM_ID
     */
    public void setPartFromId(Number value) {
        setAttributeInternal(PARTFROMID, value);
    }

    /**
     * Gets the attribute value for PARTY_TO_ID using the alias name PartyToId.
     * @return the PARTY_TO_ID
     */
    public Number getPartyToId() {
        return (Number) getAttributeInternal(PARTYTOID);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTY_TO_ID using the alias name PartyToId.
     * @param value value to set the PARTY_TO_ID
     */
    public void setPartyToId(Number value) {
        setAttributeInternal(PARTYTOID, value);
    }

    /**
     * Gets the attribute value for PARTY_FROM_ADDRESS using the alias name PartyFromAddress.
     * @return the PARTY_FROM_ADDRESS
     */
    public String getPartyFromAddress() {
        return (String) getAttributeInternal(PARTYFROMADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTY_FROM_ADDRESS using the alias name PartyFromAddress.
     * @param value value to set the PARTY_FROM_ADDRESS
     */
    public void setPartyFromAddress(String value) {
        setAttributeInternal(PARTYFROMADDRESS, value);
    }

    /**
     * Gets the attribute value for PARTY_TO_ADDRESS using the alias name PartyToAddress.
     * @return the PARTY_TO_ADDRESS
     */
    public String getPartyToAddress() {
        return (String) getAttributeInternal(PARTYTOADDRESS);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTY_TO_ADDRESS using the alias name PartyToAddress.
     * @param value value to set the PARTY_TO_ADDRESS
     */
    public void setPartyToAddress(String value) {
        setAttributeInternal(PARTYTOADDRESS, value);
    }

    /**
     * Gets the attribute value for OU_ID using the alias name OuId.
     * @return the OU_ID
     */
    public Number getOuId() {
        return (Number) getAttributeInternal(OUID);
    }

    /**
     * Sets <code>value</code> as attribute value for OU_ID using the alias name OuId.
     * @param value value to set the OU_ID
     */
    public void setOuId(Number value) {
        setAttributeInternal(OUID, value);
    }

    /**
     * Gets the attribute value for VEHICLE_TYPE using the alias name VehicleType.
     * @return the VEHICLE_TYPE
     */
    public String getVehicleType() {
        return (String) getAttributeInternal(VEHICLETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_TYPE using the alias name VehicleType.
     * @param value value to set the VEHICLE_TYPE
     */
    public void setVehicleType(String value) {
        setAttributeInternal(VEHICLETYPE, value);
    }

    /**
     * Gets the attribute value for VEHICLE_NO using the alias name VehicleNo.
     * @return the VEHICLE_NO
     */
    public String getVehicleNo() {
        return (String) getAttributeInternal(VEHICLENO);
    }

    /**
     * Sets <code>value</code> as attribute value for VEHICLE_NO using the alias name VehicleNo.
     * @param value value to set the VEHICLE_NO
     */
    public void setVehicleNo(String value) {
        setAttributeInternal(VEHICLENO, value);
    }

    /**
     * Gets the attribute value for DRIVER_NAME using the alias name DriverName.
     * @return the DRIVER_NAME
     */
    public String getDriverName() {
        return (String) getAttributeInternal(DRIVERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_NAME using the alias name DriverName.
     * @param value value to set the DRIVER_NAME
     */
    public void setDriverName(String value) {
        setAttributeInternal(DRIVERNAME, value);
    }

    /**
     * Gets the attribute value for DRIVER_PHONE using the alias name DriverPhone.
     * @return the DRIVER_PHONE
     */
    public String getDriverPhone() {
        return (String) getAttributeInternal(DRIVERPHONE);
    }

    /**
     * Sets <code>value</code> as attribute value for DRIVER_PHONE using the alias name DriverPhone.
     * @param value value to set the DRIVER_PHONE
     */
    public void setDriverPhone(String value) {
        setAttributeInternal(DRIVERPHONE, value);
    }

    /**
     * Gets the attribute value for RETURNABLE using the alias name Returnable.
     * @return the RETURNABLE
     */
    public String getReturnable() {
        return (String) getAttributeInternal(RETURNABLE);
    }

    /**
     * Sets <code>value</code> as attribute value for RETURNABLE using the alias name Returnable.
     * @param value value to set the RETURNABLE
     */
    public void setReturnable(String value) {
        setAttributeInternal(RETURNABLE, value);
    }

    /**
     * Gets the attribute value for IS_RETURNED using the alias name IsReturned.
     * @return the IS_RETURNED
     */
    public String getIsReturned() {
        return (String) getAttributeInternal(ISRETURNED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_RETURNED using the alias name IsReturned.
     * @param value value to set the IS_RETURNED
     */
    public void setIsReturned(String value) {
        setAttributeInternal(ISRETURNED, value);
    }

    /**
     * Gets the attribute value for REF_GATE_PASS_NO using the alias name RefGatePassNo.
     * @return the REF_GATE_PASS_NO
     */
    public String getRefGatePassNo() {
        return (String) getAttributeInternal(REFGATEPASSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_GATE_PASS_NO using the alias name RefGatePassNo.
     * @param value value to set the REF_GATE_PASS_NO
     */
    public void setRefGatePassNo(String value) {
        setAttributeInternal(REFGATEPASSNO, value);
    }

    /**
     * Gets the attribute value for GATE_IN_DATE using the alias name GateInDate.
     * @return the GATE_IN_DATE
     */
    public Timestamp getGateInDate() {
        return (Timestamp) getAttributeInternal(GATEINDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_IN_DATE using the alias name GateInDate.
     * @param value value to set the GATE_IN_DATE
     */
    public void setGateInDate(Timestamp value) {
        setAttributeInternal(GATEINDATE, value);
    }

    /**
     * Gets the attribute value for GATE_OUT_DATE using the alias name GateOutDate.
     * @return the GATE_OUT_DATE
     */
    public Timestamp getGateOutDate() {
        return (Timestamp) getAttributeInternal(GATEOUTDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_OUT_DATE using the alias name GateOutDate.
     * @param value value to set the GATE_OUT_DATE
     */
    public void setGateOutDate(Timestamp value) {
        setAttributeInternal(GATEOUTDATE, value);
    }

    /**
     * Gets the attribute value for GATE_IN_FLAG using the alias name GateInFlag.
     * @return the GATE_IN_FLAG
     */
    public String getGateInFlag() {
        return (String) getAttributeInternal(GATEINFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_IN_FLAG using the alias name GateInFlag.
     * @param value value to set the GATE_IN_FLAG
     */
    public void setGateInFlag(String value) {
        setAttributeInternal(GATEINFLAG, value);
    }

    /**
     * Gets the attribute value for GATE_OUT_FLAG using the alias name GateOutFlag.
     * @return the GATE_OUT_FLAG
     */
    public String getGateOutFlag() {
        return (String) getAttributeInternal(GATEOUTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for GATE_OUT_FLAG using the alias name GateOutFlag.
     * @param value value to set the GATE_OUT_FLAG
     */
    public void setGateOutFlag(String value) {
        setAttributeInternal(GATEOUTFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyFromName.
     * @return the PartyFromName
     */
    public String getPartyFromName() {
        return (String) getAttributeInternal(PARTYFROMNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyFromName.
     * @param value value to set the  PartyFromName
     */
    public void setPartyFromName(String value) {
        setAttributeInternal(PARTYFROMNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute PartyToName.
     * @return the PartyToName
     */
    public String getPartyToName() {
        return (String) getAttributeInternal(PARTYTONAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute PartyToName.
     * @param value value to set the  PartyToName
     */
    public void setPartyToName(String value) {
        setAttributeInternal(PARTYTONAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OperatingUnit.
     * @return the OperatingUnit
     */
    public String getOperatingUnit() {
        return (String) getAttributeInternal(OPERATINGUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OperatingUnit.
     * @param value value to set the  OperatingUnit
     */
    public void setOperatingUnit(String value) {
        setAttributeInternal(OPERATINGUNIT, value);
    }

    /**
     * Gets the attribute value for CREATER_NAME using the alias name CreaterName.
     * @return the CREATER_NAME
     */
    public String getCreaterName() {
        return (String) getAttributeInternal(CREATERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATER_NAME using the alias name CreaterName.
     * @param value value to set the CREATER_NAME
     */
    public void setCreaterName(String value) {
        setAttributeInternal(CREATERNAME, value);
    }

    /**
     * Gets the attribute value for LAST_EDITOR_NAME using the alias name LastEditorName.
     * @return the LAST_EDITOR_NAME
     */
    public String getLastEditorName() {
        return (String) getAttributeInternal(LASTEDITORNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_EDITOR_NAME using the alias name LastEditorName.
     * @param value value to set the LAST_EDITOR_NAME
     */
    public void setLastEditorName(String value) {
        setAttributeInternal(LASTEDITORNAME, value);
    }

    /**
     * Gets the attribute value for OPERATING_UNIT using the alias name OperatingUnit1.
     * @return the OPERATING_UNIT
     */
    public String getOperatingUnit1() {
        return (String) getAttributeInternal(OPERATINGUNIT1);
    }

    /**
     * Sets <code>value</code> as attribute value for OPERATING_UNIT using the alias name OperatingUnit1.
     * @param value value to set the OPERATING_UNIT
     */
    public void setOperatingUnit1(String value) {
        setAttributeInternal(OPERATINGUNIT1, value);
    }

    /**
     * Gets the attribute value for TIME_OUT_FLAG using the alias name TimeOutFlag.
     * @return the TIME_OUT_FLAG
     */
    public String getTimeOutFlag() {
        return (String) getAttributeInternal(TIMEOUTFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_OUT_FLAG using the alias name TimeOutFlag.
     * @param value value to set the TIME_OUT_FLAG
     */
    public void setTimeOutFlag(String value) {
        setAttributeInternal(TIMEOUTFLAG, value);
    }

    /**
     * Gets the attribute value for DISABLED_FLAG using the alias name DisabledFlag.
     * @return the DISABLED_FLAG
     */
    public String getDisabledFlag() {
        return (String) getAttributeInternal(DISABLEDFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for DISABLED_FLAG using the alias name DisabledFlag.
     * @param value value to set the DISABLED_FLAG
     */
    public void setDisabledFlag(String value) {
        setAttributeInternal(DISABLEDFLAG, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @return the APPROVAL_STATUS
     */
    public String getApprovalStatus() {
        return (String) getAttributeInternal(APPROVALSTATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS using the alias name ApprovalStatus.
     * @param value value to set the APPROVAL_STATUS
     */
    public void setApprovalStatus(String value) {
        setAttributeInternal(APPROVALSTATUS, value);
    }

    /**
     * Gets the attribute value for SOURCE using the alias name Source.
     * @return the SOURCE
     */
    public String getSource() {
        return (String) getAttributeInternal(SOURCE);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE using the alias name Source.
     * @param value value to set the SOURCE
     */
    public void setSource(String value) {
        setAttributeInternal(SOURCE, value);
    }

    /**
     * Gets the attribute value for SOURCE_DOC_NO using the alias name SourceDocNo.
     * @return the SOURCE_DOC_NO
     */
    public String getSourceDocNo() {
        return (String) getAttributeInternal(SOURCEDOCNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_DOC_NO using the alias name SourceDocNo.
     * @param value value to set the SOURCE_DOC_NO
     */
    public void setSourceDocNo(String value) {
        setAttributeInternal(SOURCEDOCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ApproveStatusMeaning.
     * @return the ApproveStatusMeaning
     */
    public String getApproveStatusMeaning() {
        return (String) getAttributeInternal(APPROVESTATUSMEANING);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public BigDecimal getLocationId() {
        return (BigDecimal) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(BigDecimal value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for PARTY_ADDRESS_GENERIC using the alias name PartyAddressGeneric.
     * @return the PARTY_ADDRESS_GENERIC
     */
    public String getPartyAddressGeneric() {
        return (String) getAttributeInternal(PARTYADDRESSGENERIC);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTY_ADDRESS_GENERIC using the alias name PartyAddressGeneric.
     * @param value value to set the PARTY_ADDRESS_GENERIC
     */
    public void setPartyAddressGeneric(String value) {
        setAttributeInternal(PARTYADDRESSGENERIC, value);
    }

    /**
     * Gets the attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @return the ORGANIZATION_ID
     */
    public String getOrganizationId() {
        return (String) getAttributeInternal(ORGANIZATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORGANIZATION_ID using the alias name OrganizationId.
     * @param value value to set the ORGANIZATION_ID
     */
    public void setOrganizationId(String value) {
        setAttributeInternal(ORGANIZATIONID, value);
    }


    /**
     * Gets the attribute value for the calculated attribute SumofLineQty.
     * @return the SumofLineQty
     */
    public String getSumofLineQty() {
        return (String) getAttributeInternal(SUMOFLINEQTY);
    }


    /**
     * Gets the attribute value for the calculated attribute Org_Nam.
     * @return the Org_Nam
     */
    public String getOrg_Nam() {
        return (String) getAttributeInternal(ORG_NAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Org_Nam.
     * @param value value to set the  Org_Nam
     */
    public void setOrg_Nam(String value) {
        setAttributeInternal(ORG_NAM, value);
    }

    /**
     * Gets the attribute value for INTERNAL using the alias name Internal.
     * @return the INTERNAL
     */
    public String getInternal() {
        return (String) getAttributeInternal(INTERNAL);
    }

    /**
     * Sets <code>value</code> as attribute value for INTERNAL using the alias name Internal.
     * @param value value to set the INTERNAL
     */
    public void setInternal(String value) {
        setAttributeInternal(INTERNAL, value);


        if (value.equals("Y")) {
            this.setVehicleNo("N/A");
            this.setVehicleType("N/A");
            this.setDriverName("N/A");
            this.setDriverPhone("N/A");

        } else {
            this.setVehicleNo("");
            this.setVehicleType("");
            this.setDriverName("");
            this.setDriverPhone("");
        }

    }

    /**
     * Gets the attribute value for CARRIER using the alias name Carrier.
     * @return the CARRIER
     */
    public String getCarrier() {
        return (String) getAttributeInternal(CARRIER);
    }

    /**
     * Sets <code>value</code> as attribute value for CARRIER using the alias name Carrier.
     * @param value value to set the CARRIER
     */
    public void setCarrier(String value) {
        setAttributeInternal(CARRIER, value);
    }

    /**
     * Gets the attribute value for LICENCE_NO using the alias name LicenceNo.
     * @return the LICENCE_NO
     */
    public String getLicenceNo() {
        return (String) getAttributeInternal(LICENCENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LICENCE_NO using the alias name LicenceNo.
     * @param value value to set the LICENCE_NO
     */
    public void setLicenceNo(String value) {
        setAttributeInternal(LICENCENO, value);
    }

    /**
     * Gets the attribute value for LOCK_NO using the alias name LockNo.
     * @return the LOCK_NO
     */
    public String getLockNo() {
        return (String) getAttributeInternal(LOCKNO);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCK_NO using the alias name LockNo.
     * @param value value to set the LOCK_NO
     */
    public void setLockNo(String value) {
        setAttributeInternal(LOCKNO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcGatePassLinesVO.
     */
    public RowIterator getPwcGatePassLinesVO() {
        return (RowIterator) getAttributeInternal(PWCGATEPASSLINESVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link PwcPopulateSearchVO.
     */
    public RowIterator getPwcPopulateSearchVO() {
        return (RowIterator) getAttributeInternal(PWCPOPULATESEARCHVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartiesAddressLOV1.
     */
    public RowSet getPartiesAddressLOV1() {
        return (RowSet) getAttributeInternal(PARTIESADDRESSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartiesAddressLOV2.
     */
    public RowSet getPartiesAddressLOV2() {
        return (RowSet) getAttributeInternal(PARTIESADDRESSLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartiesLOV1.
     */
    public RowSet getPartiesLOV1() {
        return (RowSet) getAttributeInternal(PARTIESLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PartiesLOV2.
     */
    public RowSet getPartiesLOV2() {
        return (RowSet) getAttributeInternal(PARTIESLOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VehicleTypeLOV1.
     */
    public RowSet getVehicleTypeLOV1() {
        return (RowSet) getAttributeInternal(VEHICLETYPELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GatePassTypeLOV1.
     */
    public RowSet getGatePassTypeLOV1() {
        return (RowSet) getAttributeInternal(GATEPASSTYPELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> GatePassClass1.
     */
    public RowSet getGatePassClass1() {
        return (RowSet) getAttributeInternal(GATEPASSCLASS1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OperatingUnitsLOV1.
     */
    public RowSet getOperatingUnitsLOV1() {
        return (RowSet) getAttributeInternal(OPERATINGUNITSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> RefGatePassLOV1.
     */
    public RowSet getRefGatePassLOV1() {
        return (RowSet) getAttributeInternal(REFGATEPASSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SourceLOV1.
     */
    public RowSet getSourceLOV1() {
        return (RowSet) getAttributeInternal(SOURCELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SourcesDocNoLOV1.
     */
    public RowSet getSourcesDocNoLOV1() {
        return (RowSet) getAttributeInternal(SOURCESDOCNOLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV1.
     */
    public RowSet getORG_NAME_LOV1() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV2.
     */
    public RowSet getORG_NAME_LOV2() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV2);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV3.
     */
    public RowSet getORG_NAME_LOV3() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV3);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV4.
     */
    public RowSet getORG_NAME_LOV4() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV4);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV5.
     */
    public RowSet getORG_NAME_LOV5() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV5);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV6.
     */
    public RowSet getORG_NAME_LOV6() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV6);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV7.
     */
    public RowSet getORG_NAME_LOV7() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV7);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ORG_NAME_LOV8.
     */
    public RowSet getORG_NAME_LOV8() {
        return (RowSet) getAttributeInternal(ORG_NAME_LOV8);
    }
}

