package model.VO;

import java.math.BigDecimal;

import java.sql.Timestamp;

import model.EO.PwcGatePassDetailsImpl;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Apr 19 15:10:33 BDT 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PwcGatePassDetailsVORowImpl extends ViewRowImpl {

    public static final int ENTITY_PWCGATEPASSDETAILS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        LineId,
        DetailId,
        LineCode,
        ItemId,
        Quantity,
        Uom,
        CreatedBy,
        CreationDate,
        LastUpdatedBy,
        LastUpdateDate,
        RefLineId,
        ItemDetails,
        ItemDesc,
        SourceId,
        SecondaryQty,
        SecondaryUom,
        Remarks,
        TotalSecondaryQty,
        TotalQty,
        PartialChallan,
        LineSource,
        PwcGatePassLinesVO,
        UomLOV1,
        secuom1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int DETAILID = AttributesEnum.DetailId.index();
    public static final int LINECODE = AttributesEnum.LineCode.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int REFLINEID = AttributesEnum.RefLineId.index();
    public static final int ITEMDETAILS = AttributesEnum.ItemDetails.index();
    public static final int ITEMDESC = AttributesEnum.ItemDesc.index();
    public static final int SOURCEID = AttributesEnum.SourceId.index();
    public static final int SECONDARYQTY = AttributesEnum.SecondaryQty.index();
    public static final int SECONDARYUOM = AttributesEnum.SecondaryUom.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int TOTALSECONDARYQTY = AttributesEnum.TotalSecondaryQty.index();
    public static final int TOTALQTY = AttributesEnum.TotalQty.index();
    public static final int PARTIALCHALLAN = AttributesEnum.PartialChallan.index();
    public static final int LINESOURCE = AttributesEnum.LineSource.index();
    public static final int PWCGATEPASSLINESVO = AttributesEnum.PwcGatePassLinesVO.index();
    public static final int UOMLOV1 = AttributesEnum.UomLOV1.index();
    public static final int SECUOM1 = AttributesEnum.secuom1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PwcGatePassDetailsVORowImpl() {
    }

    /**
     * Gets PwcGatePassDetails entity object.
     * @return the PwcGatePassDetails
     */
    public PwcGatePassDetailsImpl getPwcGatePassDetails() {
        return (PwcGatePassDetailsImpl) getEntity(ENTITY_PWCGATEPASSDETAILS);
    }

    /**
     * Gets the attribute value for LINE_ID using the alias name LineId.
     * @return the LINE_ID
     */
    public BigDecimal getLineId() {
        return (BigDecimal) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId.
     * @param value value to set the LINE_ID
     */
    public void setLineId(BigDecimal value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for DETAIL_ID using the alias name DetailId.
     * @return the DETAIL_ID
     */
    public Number getDetailId() {
        return (Number) getAttributeInternal(DETAILID);
    }

    /**
     * Sets <code>value</code> as attribute value for DETAIL_ID using the alias name DetailId.
     * @param value value to set the DETAIL_ID
     */
    public void setDetailId(Number value) {
        setAttributeInternal(DETAILID, value);
    }

    /**
     * Gets the attribute value for LINE_CODE using the alias name LineCode.
     * @return the LINE_CODE
     */
    public String getLineCode() {
        return (String) getAttributeInternal(LINECODE);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_CODE using the alias name LineCode.
     * @param value value to set the LINE_CODE
     */
    public void setLineCode(String value) {
        setAttributeInternal(LINECODE, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public BigDecimal getItemId() {
        return (BigDecimal) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(BigDecimal value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for QUANTITY using the alias name Quantity.
     * @return the QUANTITY
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity.
     * @param value value to set the QUANTITY
     */
    public void setQuantity(BigDecimal value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for UOM using the alias name Uom.
     * @return the UOM
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as attribute value for UOM using the alias name Uom.
     * @param value value to set the UOM
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Timestamp getCreationDate() {
        return (Timestamp) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Timestamp getLastUpdateDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for REF_LINE_ID using the alias name RefLineId.
     * @return the REF_LINE_ID
     */
    public Number getRefLineId() {
        return (Number) getAttributeInternal(REFLINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for REF_LINE_ID using the alias name RefLineId.
     * @param value value to set the REF_LINE_ID
     */
    public void setRefLineId(Number value) {
        setAttributeInternal(REFLINEID, value);
    }

    /**
     * Gets the attribute value for ITEM_DETAILS using the alias name ItemDetails.
     * @return the ITEM_DETAILS
     */
    public String getItemDetails() {
        return (String) getAttributeInternal(ITEMDETAILS);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DETAILS using the alias name ItemDetails.
     * @param value value to set the ITEM_DETAILS
     */
    public void setItemDetails(String value) {
        setAttributeInternal(ITEMDETAILS, value);
    }

    /**
     * Gets the attribute value for ITEM_DESC using the alias name ItemDesc.
     * @return the ITEM_DESC
     */
    public String getItemDesc() {
        return (String) getAttributeInternal(ITEMDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESC using the alias name ItemDesc.
     * @param value value to set the ITEM_DESC
     */
    public void setItemDesc(String value) {
        setAttributeInternal(ITEMDESC, value);
    }

    /**
     * Gets the attribute value for SOURCE_ID using the alias name SourceId.
     * @return the SOURCE_ID
     */
    public BigDecimal getSourceId() {
        return (BigDecimal) getAttributeInternal(SOURCEID);
    }

    /**
     * Sets <code>value</code> as attribute value for SOURCE_ID using the alias name SourceId.
     * @param value value to set the SOURCE_ID
     */
    public void setSourceId(BigDecimal value) {
        setAttributeInternal(SOURCEID, value);
    }

    /**
     * Gets the attribute value for SECONDARY_QTY using the alias name SecondaryQty.
     * @return the SECONDARY_QTY
     */
    public BigDecimal getSecondaryQty() {
        return (BigDecimal) getAttributeInternal(SECONDARYQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SECONDARY_QTY using the alias name SecondaryQty.
     * @param value value to set the SECONDARY_QTY
     */
    public void setSecondaryQty(BigDecimal value) {
        setAttributeInternal(SECONDARYQTY, value);
    }

    /**
     * Gets the attribute value for SECONDARY_UOM using the alias name SecondaryUom.
     * @return the SECONDARY_UOM
     */
    public String getSecondaryUom() {
        return (String) getAttributeInternal(SECONDARYUOM);
    }

    /**
     * Sets <code>value</code> as attribute value for SECONDARY_UOM using the alias name SecondaryUom.
     * @param value value to set the SECONDARY_UOM
     */
    public void setSecondaryUom(String value) {
        setAttributeInternal(SECONDARYUOM, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for TOTAL_SECONDARY_QTY using the alias name TotalSecondaryQty.
     * @return the TOTAL_SECONDARY_QTY
     */
    public BigDecimal getTotalSecondaryQty() {
        return (BigDecimal) getAttributeInternal(TOTALSECONDARYQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_SECONDARY_QTY using the alias name TotalSecondaryQty.
     * @param value value to set the TOTAL_SECONDARY_QTY
     */
    public void setTotalSecondaryQty(BigDecimal value) {
        setAttributeInternal(TOTALSECONDARYQTY, value);
    }

    /**
     * Gets the attribute value for TOTAL_QTY using the alias name TotalQty.
     * @return the TOTAL_QTY
     */
    public BigDecimal getTotalQty() {
        return (BigDecimal) getAttributeInternal(TOTALQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_QTY using the alias name TotalQty.
     * @param value value to set the TOTAL_QTY
     */
    public void setTotalQty(BigDecimal value) {
        setAttributeInternal(TOTALQTY, value);
    }

    /**
     * Gets the attribute value for PARTIAL_CHALLAN using the alias name PartialChallan.
     * @return the PARTIAL_CHALLAN
     */
    public String getPartialChallan() {
        return (String) getAttributeInternal(PARTIALCHALLAN);
    }

    /**
     * Sets <code>value</code> as attribute value for PARTIAL_CHALLAN using the alias name PartialChallan.
     * @param value value to set the PARTIAL_CHALLAN
     */
    public void setPartialChallan(String value) {
        setAttributeInternal(PARTIALCHALLAN, value);
        if (value.equals("n")){
            this.setQuantity(this.getTotalQty());
            this.setSecondaryQty(this.getTotalSecondaryQty());
        }
        
    }

    /**
     * Gets the attribute value for the calculated attribute LineSource.
     * @return the LineSource
     */
    public String getLineSource() {
      return (String) this.getPwcGatePassLinesVO().getAttribute("Source");
      //  return (String) getAttributeInternal(LINESOURCE);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link PwcGatePassLinesVO.
     */
    public Row getPwcGatePassLinesVO() {
        return (Row) getAttributeInternal(PWCGATEPASSLINESVO);
    }

    /**
     * Sets the master-detail link PwcGatePassLinesVO between this object and <code>value</code>.
     */
    public void setPwcGatePassLinesVO(Row value) {
        setAttributeInternal(PWCGATEPASSLINESVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> UomLOV1.
     */
    public RowSet getUomLOV1() {
        return (RowSet) getAttributeInternal(UOMLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> secuom1.
     */
    public RowSet getsecuom1() {
        return (RowSet) getAttributeInternal(SECUOM1);
    }
}

