package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jul 22 12:16:33 BDT 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LogisticPartyLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LogisticPartyLOVImpl() {
    }
}

