package model.LOV;

import java.math.BigDecimal;

import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 19:06:19 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PopulateLinesDataVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        Source,
        SourceDocNo,
        DeliveryChallanNo,
        ItemDetails,
        Description,
        Quantity,
        Uom,
        SecondaryQty,
        SecondaryUom,
        SourceId,
        ShipToLocation,
        selectFlag;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SOURCE = AttributesEnum.Source.index();
    public static final int SOURCEDOCNO = AttributesEnum.SourceDocNo.index();
    public static final int DELIVERYCHALLANNO = AttributesEnum.DeliveryChallanNo.index();
    public static final int ITEMDETAILS = AttributesEnum.ItemDetails.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int SECONDARYQTY = AttributesEnum.SecondaryQty.index();
    public static final int SECONDARYUOM = AttributesEnum.SecondaryUom.index();
    public static final int SOURCEID = AttributesEnum.SourceId.index();
    public static final int SHIPTOLOCATION = AttributesEnum.ShipToLocation.index();
    public static final int SELECTFLAG = AttributesEnum.selectFlag.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PopulateLinesDataVORowImpl() {
    }
}

