package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Dec 03 13:20:43 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class secuomImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public secuomImpl() {
    }
}

