package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jun 23 19:46:24 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SourcesDocNoLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SourcesDocNoLOVImpl() {
    }
}

