package model.LOV;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 19 17:43:41 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class VehicleTypeLOVImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public VehicleTypeLOVImpl() {
    }
}

