package model.AM.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 21 13:33:07 PKT 2022
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    Row createLines();

    String getPopulateValues(Row poprow, String columnName);

    void populateLines();

    Row populateLinesData();

    void setpopulateLines(Row poprow);

    void populateDetails();

    Row populateDetailsData();

    void setpopulateDetails(Row poprow);

    void populateLinesDialogListener();

    void populateLinesDialogListenerNew(String source, String sourceDocNo);

    void popupFetchListener();

    Row createHeaderLines();

    void populateHeader();

    void gateOutActionBind();

    void getParameters();

    void createBtnLines();

    void populateBtnListener();

    String sendNotifyforApproval();

    void popupFetchListenerNew();

    void createDeatailAL();

    void SaveButtonActionListenerAM();

    String AttachementActionListener();

    String SaveButtonActionListenerAM2();

    void reverseGatePass();
}

